DEVISE_SECRET_KEY: [FILL IN DETAILS]

# Needed for Twitter Authentication
TWITTER_KEY: [FILL IN DETAILS]
TWITTER_SECRET: [FILL IN DETAILS]

# For use with Sendgrid and Heroku
SENDGRID_USERNAME: [FILL IN DETAILS]
SENDGRID_PASSWORD: [FILL IN DETAILS]

SECRET_KEY_BASE: [FILL IN DETAILS]
